openapi: 3.0.3
info:
  title: 'HEMIS University API - Master Documentation'
  description: "**HEMIS University Management System - Complete API**\n\nSingle Source of Truth for all API endpoints.\n\n## Authentication\n```\nPOST /api/v1/employee/auth/login\nPOST /api/v1/student/auth/login\nAuthorization: Bearer {token}\n```\n\n## Permission System\n\nHar bir endpoint quyidagi meta-data'ga ega:\n- **x-permissions**: Required permissions (any of these)\n- **x-roles**: Allowed roles (any of these)\n- **x-user-types**: User categories (employee, student, admin)\n\n## Base URL\n- Development: http://localhost:8000/api\n- Production: https://hemis.uz/api\n"
  version: 1.0.0
  contact:
    name: 'HEMIS Support'
    email: support@hemis.uz
servers:
  -
    url: 'http://localhost:8000/api'
    description: 'Development server'
  -
    url: 'https://hemis.uz/api'
    description: 'Production server'
tags:
  -
    name: Auth
    description: 'Authentication endpoints'
  -
    name: 'Teacher - Dashboard'
    description: "O'qituvchi dashboard"
  -
    name: 'Teacher - Schedule'
    description: 'Dars jadvali'
  -
    name: 'Teacher - Attendance'
    description: Davomat
  -
    name: 'Teacher - Grades'
    description: Baholar
  -
    name: 'Teacher - Subjects'
    description: Fanlar
  -
    name: 'Teacher - Students'
    description: Talabalar
  -
    name: 'Student - Dashboard'
    description: 'Talaba dashboard'
  -
    name: 'Student - Profile'
    description: "Shaxsiy ma'lumotlar"
  -
    name: 'Admin - Dashboard'
    description: 'Admin dashboard'
  -
    name: 'Admin - Users'
    description: Foydalanuvchilar
  -
    name: Integration
    description: 'Tashqi integratsiya'
security:
  -
    BearerAuth: {  }
paths:
  /v1/employee/auth/login:
    post:
      tags:
        - Auth
      summary: 'Employee login (Teachers, Admins, Staff)'
      x-permissions: {  }
      x-roles: {  }
      x-user-types:
        - public
      x-auth-required: false
      security: {  }
      operationId: employeeLogin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - login
                - password
              properties:
                login:
                  type: string
                  example: jora_kuvandikov
                password:
                  type: string
                  example: password
      responses:
        200:
          description: 'Muvaffaqiyatli login'
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: { type: boolean }
                  data: { type: object, properties: { token: { type: string }, user: { type: object } } }
  /v1/student/auth/login:
    post:
      tags:
        - Auth
      summary: 'Student login'
      x-permissions: {  }
      x-roles: {  }
      x-user-types:
        - public
      x-auth-required: false
      security: {  }
      operationId: studentLogin
      responses:
        200:
          description: 'Muvaffaqiyatli login'
  /v1/student/dashboard:
    get:
      tags:
        - 'Student - Dashboard'
      summary: 'Talaba dashboard'
      x-permissions:
        - student.dashboard.view
        - admin.student.view
      x-roles:
        - student
        - graduate_student
        - admin
      x-user-types:
        - student
        - employee
      responses:
        200:
          description: "Dashboard ma'lumotlari"
  /v1/student/profile:
    get:
      tags:
        - 'Student - Profile'
      summary: "Shaxsiy ma'lumotlar"
      x-permissions:
        - student.profile.view
      x-roles:
        - student
        - graduate_student
      x-user-types:
        - student
      responses:
        200:
          description: Profile
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 'JWT token authentication'
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
      description: 'API Key for integration'
  schemas:
    SuccessResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: 'Operation completed successfully'
        data:
          type: object
    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
          example: 'Error message'
        errors:
          type: object
    PaginationMeta:
      type: object
      properties:
        current_page:
          type: integer
          example: 1
        last_page:
          type: integer
          example: 10
        per_page:
          type: integer
          example: 20
        total:
          type: integer
          example: 195
    DashboardData:
      type: object
      properties:
        stats:
          type: object
          properties:
            total_subjects:
              type: integer
              example: 5
              description: "O'qitiladigan fanlar soni"
            total_groups:
              type: integer
              example: 8
              description: 'Guruhlar soni'
            total_students:
              type: integer
              example: 142
              description: 'Talabalar soni'
            pending_attendance:
              type: integer
              example: 3
              description: 'Davomat qilinmagan darslar'
            ungraded_assignments:
              type: integer
              example: 12
              description: 'Baholanmagan topshiriqlar'
        today_schedule:
          type: array
          items:
            $ref: '#/components/schemas/ScheduleItem'
        pending_attendance_classes:
          type: array
          items:
            $ref: '#/components/schemas/PendingAttendanceClass'
        recent_activities:
          type: array
          items:
            $ref: '#/components/schemas/Activity'
    PendingAttendanceClass:
      type: object
      properties:
        id:
          type: integer
          example: 1234
        lesson_date:
          type: string
          format: date
          example: '2025-01-02'
        days_ago:
          type: integer
          example: 2
        subject_name:
          type: string
          example: Matematika
        group_name:
          type: string
          example: 21-guruh
        lesson_pair:
          type: integer
          example: 3
        audience:
          type: string
          example: A-201
    Activity:
      type: object
      properties:
        type:
          type: string
          enum:
            - attendance
            - grade
            - assignment
          example: attendance
        date:
          type: string
          format: date-time
          example: '2025-01-04T10:30:00Z'
        description:
          type: string
          example: 'Davomat belgilandi - Matematika, 21-guruh'
        student:
          type: string
          example: 'Aliyev Vali'
    ScheduleItem:
      type: object
      properties:
        id:
          type: integer
          example: 5678
        lesson_date:
          type: string
          format: date
          example: '2025-01-04'
        lesson_pair:
          type: integer
          example: 2
          description: 'Dars jufti (1-6)'
        start_time:
          type: string
          example: '09:00'
        end_time:
          type: string
          example: '10:30'
        subject:
          $ref: '#/components/schemas/Subject'
        group:
          $ref: '#/components/schemas/Group'
        audience:
          type: string
          example: A-301
        lesson_type:
          type: string
          enum:
            - lecture
            - practical
            - laboratory
            - seminar
          example: lecture
        has_attendance:
          type: boolean
          example: false
    WorkloadData:
      type: object
      properties:
        total_hours:
          type: integer
          example: 360
          description: 'Jami soatlar'
        completed_hours:
          type: integer
          example: 120
          description: "O'tilgan soatlar"
        remaining_hours:
          type: integer
          example: 240
        subjects:
          type: array
          items:
            type: object
            properties:
              subject_name:
                type: string
                example: Matematika
              total_hours:
                type: integer
                example: 72
              completed_hours:
                type: integer
                example: 24
              groups:
                type: array
                items:
                  type: string
                example:
                  - 21-guruh
                  - 22-guruh
    AttendanceRequest:
      type: object
      required:
        - subject_schedule_id
        - date
        - attendance
      properties:
        subject_schedule_id:
          type: integer
          example: 1234
          description: 'Dars jadvali ID'
        date:
          type: string
          format: date
          example: '2025-01-04'
        attendance:
          type: array
          items:
            type: object
            required:
              - student_id
              - status
            properties:
              student_id:
                type: integer
                example: 5678
              status:
                type: integer
                enum:
                  - 1
                  - 2
                  - 3
                example: 1
                description: '1=Keldi, 2=Kelmadi, 3=Sababli'
              reason:
                type: string
                example: Kasallik
                description: 'Sabab (agar status=3)'
    AttendanceData:
      type: object
      properties:
        id:
          type: integer
          example: 9876
        subject_schedule_id:
          type: integer
          example: 1234
        lesson_date:
          type: string
          format: date
          example: '2025-01-04'
        subject:
          $ref: '#/components/schemas/Subject'
        group:
          $ref: '#/components/schemas/Group'
        students:
          type: array
          items:
            type: object
            properties:
              student_id:
                type: integer
                example: 5678
              student_name:
                type: string
                example: 'Aliyev Vali'
              status:
                type: integer
                example: 1
              reason:
                type: string
                example: Kasallik
    GradeRequest:
      type: object
      required:
        - student_id
        - subject_id
        - grade_type
        - grade
      properties:
        student_id:
          type: integer
          example: 5678
        subject_id:
          type: integer
          example: 123
        grade_type:
          type: string
          enum:
            - current
            - midterm
            - final
            - attendance
          example: midterm
          description: 'Baho turi'
        grade:
          type: number
          format: float
          example: 85.5
          minimum: 0
          maximum: 100
        comment:
          type: string
          example: 'Yaxshi ishladi'
    GradeData:
      type: object
      properties:
        id:
          type: integer
          example: 4567
        student:
          $ref: '#/components/schemas/Student'
        subject:
          $ref: '#/components/schemas/Subject'
        grade_type:
          type: string
          example: midterm
        grade:
          type: number
          example: 85.5
        max_grade:
          type: number
          example: 100
        comment:
          type: string
          example: 'Yaxshi ishladi'
        created_at:
          type: string
          format: date-time
          example: '2025-01-04T14:30:00Z'
    Subject:
      type: object
      properties:
        id:
          type: integer
          example: 123
        name:
          type: string
          example: Matematika
        code:
          type: string
          example: MATH-101
        credit:
          type: integer
          example: 4
        semester:
          type: integer
          example: 2
    Group:
      type: object
      properties:
        id:
          type: integer
          example: 456
        name:
          type: string
          example: 21-guruh
        code:
          type: string
          example: IT-21-01
        course:
          type: integer
          example: 2
        students_count:
          type: integer
          example: 28
    Student:
      type: object
      properties:
        id:
          type: integer
          example: 5678
        full_name:
          type: string
          example: 'Aliyev Vali'
        student_id_number:
          type: string
          example: '2021001234'
        group:
          $ref: '#/components/schemas/Group'
        phone:
          type: string
          example: '+998901234567'
        email:
          type: string
          example: v.aliyev@student.uz
  responses:
    UnauthorizedError:
      description: "Token yo'q yoki yaroqsiz"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            success: false
            message: 'Unauthenticated - Token not provided or invalid'
    ForbiddenError:
      description: "Ruxsat yo'q"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            success: false
            message: "Forbidden - You don't have permission to access this resource"
    NotFoundError:
      description: "Ma'lumot topilmadi"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            success: false
            message: 'Resource not found'
    ValidationError:
      description: 'Validatsiya xatosi'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            success: false
            message: 'Validation failed'
            errors:
              student_id:
                - 'The student_id field is required'
              grade:
                - 'The grade must be between 0 and 100'
